# Generated by Django 4.2.27 on 2026-01-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_commentlike_postlike_usercomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='editedPost',
            field=models.BooleanField(default=False),
        ),
    ]
