# Generated by Django 4.2.27 on 2026-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_userpost_editedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='imageurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
